### ISSUE TITLE
Comments in default incorrect order

### ISSUE THREAD

**Issue by FrostFizzie** [dejvokep/boosted-yaml#23]
Version: 1.3.2

Comments are loaded in wrong place when creating a YAML file with the default values, like for me they should be set at the bottom.

Environment: 
Minecraft Velocity Server

Expected: 
- Comments are put in the same place as the file within the resources directory within the project

Result: 
- Comments are loaded are the very top regardless of where they should be. 

![image](https://github.com/dejvokep/boosted-yaml/assets/95259215/6f537d80-d6b6-4b36-90ea-9d64988d3002)
![image](https://github.com/dejvokep/boosted-yaml/assets/95259215/e1049aa2-ffb0-48b9-945d-54a27973c3d2)

**Comment by dejvokep** [comment]
Hey, @FrostFizzie, thanks for reporting the issue. I believe this was an issue with SnakeYAML Engine, due to which I decided to make it so all comments are moved before their respective nodes as opposed to after. I will further look into the issue and will let you know about any updates the following days. Thanks for patience.
