### ISSUE TITLE
The boosted-yaml-spigot 1.5 on maven central is empty

### ISSUE THREAD

**Issue by marlester-dev** [dejvokep/boosted-yaml#29]
It only has the SpigotSerializer class and the whole library doesn't appear when you add it as a dependency

**Comment by dejvokep** [comment]
Good day,

Beginning with the v1.5 release of BoostedYAML for Spigot, the core library is no longer distributed together with the artifact. This is due to the fact that whenever a new release comes out for the core library, a new release also has to be made for the "for Spigot" implementation, even though it doesn't include any changes.

That means, you will need to include also a dependency for the core BoostedYAML artifact in your project, alongside the already depended-on Spigot implementation, which in fact, only contains the `SpigotSerializer` class. Please refer to the documentation on the wiki to adjust to this change.

Attaching a quote from the v1.5 release notes:
> "The core BoostedYAML artifact is no longer packaged with the releases of BoostedYAML for Spigot. This change was introduced in order to isolate the development of the two projects, with no need to create releases when nothing, but the dependency (core project) has changed."

In case of any further questions, do not hesitate to ask. Have a great weekend.
~ dejvokep
