### ISSUE TITLE
Some build options to allow the way to not remove  quotes even if they are not needed.

### ISSUE THREAD

**Issue by noaskers** [dejvokep/boosted-yaml#40]
Some build options to allow the way to not remove  quotes even if they are not needed.

Some configs would be way easier to understand for a' lot of users

**Comment by dejvokep** [comment]
Hello,

The requested behavior can already be configured with the help of scalar formatters, available in BoostedYAML since v1.3.6. Please learn more and look at an example which might suit your needs [here](https://dejvokep.gitbook.io/boostedyaml/settings/dumpersettings#example-leave-all-string-keys-plain-unquoted-and-quote-all-string-values).

Have a great day.
~ dejvokep

**Comment by noaskers** [comment]
Thanks, 

But I would like to make it so that if something is quoted it does not remove it 
But I don't wanna make everything quoted

**Comment by dejvokep** [comment]
Good evening, I see what you're trying to achieve, unfortunately, information about scalar quotation is not retained. However, if you don't mind having fixed quotation for specific elements in the document, the inbuilt scalar formatters can be utilised for your case (compare the role and value to quote only certain entries).
